In [1]:
#3 parts; 1: data preprocessing, 2:Building NN, 3:Prediction & Evaluation

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
cust_df = pd.read_csv('d:/dataset/customerchurn.csv')

In [4]:
cust_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#DATA PREPROCESSING STEP

In [6]:
X = cust_df.iloc[:,3:13].values

In [7]:
y = cust_df.iloc[:,13].values

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [10]:
labelencoder_X_1 = LabelEncoder()

In [11]:
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

In [12]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
labelencoder_x_2 = LabelEncoder()

In [14]:
X[:,2] = labelencoder_x_2.fit_transform(X[:,2])

In [15]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
#for Geography

onehotencoder = OneHotEncoder(categorical_features=[1])

In [17]:
X = onehotencoder.fit_transform(X).toarray()

C:\Users\abdul\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\abdul\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [18]:
X.shape

(10000, 12)

In [19]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
X = X[:,1:]

In [21]:
X.shape

(10000, 11)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test, y_train,y_test = train_test_split(X,y, test_size=0.25)

In [24]:
#feature scaling -- required for deep learning

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [25]:
import keras

Using TensorFlow backend.


In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [27]:
#initialize the NN

customer_classifier = Sequential()

In [28]:
#adding first input layer and hidden layer

customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu',input_dim=11))

C:\Users\abdul\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [29]:
#second hidden layer
customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu'))

C:\Users\abdul\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [30]:
#third hidden layer
customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu'))

C:\Users\abdul\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [31]:
customer_classifier.add(Dense(output_dim = 1, init = 'uniform',activation='sigmoid'))

C:\Users\abdul\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
#compile
customer_classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [33]:
customer_classifier.fit(X_train,y_train,batch_size=10,nb_epoch=300)

C:\Users\abdul\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/300
7500/7500 [==============================] - 4s 475us/step - loss: 0.4886 - accuracy: 0.7945
Epoch 2/300
7500/7500 [==============================] - 2s 213us/step - loss: 0.4223 - accuracy: 0.79480s - loss: 0.426
Epoch 3/300
7500/7500 [==============================] - 2s 206us/step - loss: 0.4160 - accuracy: 0.8087
Epoch 4/300
7500/7500 [==============================] - 2s 217us/step - loss: 0.4128 - accuracy: 0.8284
Epoch 5/300
7500/7500 [==============================] - 2s 207us/step - loss: 0.4102 - accuracy: 0.8336
Epoch 6/300
7500/7500 [==============================] - 2s 210us/step - loss: 0.4083 - accuracy: 0.8344
Epoch 7/300
7500/7500 [==============================] - 2s 217us/step - loss: 0.4064 - accuracy: 0.8375
Epoch 8/300
7500/7500 [==============================] - 2s 209us/step - loss: 0.4046 - accuracy: 0.8356
Epoch 9/300
7500/7500 [==============================] - 2s 211us/step - loss: 0.4035 - accuracy: 0.8377
Epoch 10/300
7500/7500 [===============

#200 epochs 
loss: 0.3889 - accuracy: 0.8424

#300 epochs
loss: 0.3885 - accuracy: 0.8428
        
#with three hidden layers
loss: 0.3885 - accuracy: 0.8428


In [34]:
predictions = customer_classifier.predict(X_test)

In [35]:
predictions

array([[0.19943735],
       [0.24256527],
       [0.01258847],
       ...,
       [0.04772026],
       [0.20202003],
       [0.01648543]], dtype=float32)

In [36]:
predictions [predictions > 0.50]

array([0.5250465 , 0.70469296, 0.52646387, 0.5708631 , 0.9561365 ,
       0.90957355, 0.86833906, 0.55384517, 0.69690317, 0.8786441 ,
       0.7796179 , 0.8571775 , 0.5424065 , 0.9561365 , 0.6620451 ,
       0.58930486, 0.8879441 , 0.78076655, 0.85152596, 0.6545615 ,
       0.6966347 , 0.63047826, 0.5855626 , 0.9561365 , 0.6156502 ,
       0.9561365 , 0.8186142 , 0.6239474 , 0.5586498 , 0.9561365 ,
       0.64739954, 0.68254566, 0.9561365 , 0.9561365 , 0.5755612 ,
       0.83240914, 0.6090769 , 0.94736826, 0.9561365 , 0.53301203,
       0.6452181 , 0.567491  , 0.65021765, 0.65212774, 0.9561365 ,
       0.7421742 , 0.6585463 , 0.7030073 , 0.8927306 , 0.86540526,
       0.52840126, 0.76533794, 0.73960006, 0.61879   , 0.6293018 ,
       0.91891634, 0.93112504, 0.52762574, 0.72227776, 0.54624754,
       0.5580486 , 0.53110677, 0.5937949 , 0.5434816 , 0.513875  ,
       0.5361966 , 0.61903214, 0.7425712 , 0.7054885 , 0.5561688 ,
       0.8168739 , 0.90757763, 0.6450994 , 0.575356  , 0.95613

In [37]:
customer_classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 7         
Total params: 163
Trainable params: 163
Non-trainable params: 0
_________________________________________________________________


In [38]:
customer_classifier.save('d:/dataset/customer_churn_model.h5')

In [39]:
from keras.models import load_model
customer_churn = load_model('d:/dataset/customer_churn_model.h5')

#customer_churn.predict()

In [40]:
predictions

array([[0.19943735],
       [0.24256527],
       [0.01258847],
       ...,
       [0.04772026],
       [0.20202003],
       [0.01648543]], dtype=float32)

In [41]:
pred_y = [predictions >= 0.50]

In [47]:
len(pred_y)

1

In [46]:
len(y_test)

2500

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [48]:
CM = confusion_matrix(y_test,pred_y[0])

In [49]:
CM

array([[1893,  109],
       [ 266,  232]], dtype=int64)